// Generate all remaining server definitions for MEGA Gateway Cloud
// Outputs SQL INSERT statements to be run against D1

const DB_ID = '5b92a2cc-01fe-4264-a201-e22972bc479e';

// ============================================================================
// SERVER DEFINITIONS BY CATEGORY
// Each server: [name, description, api_base_url, auth_type, auth_key_name]
// ============================================================================

const SERVERS = {
  AI_ML: [
    // Additional AI/ML servers beyond the 40 already inserted
    ['amazon-bedrock-agents','AWS Bedrock Agents — autonomous AI agents','https://bedrock-agent-runtime.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['amazon-comprehend','AWS Comprehend — NLP text analysis','https://comprehend.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['amazon-rekognition','AWS Rekognition — image/video analysis','https://rekognition.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['amazon-textract','AWS Textract — document text extraction','https://textract.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['amazon-transcribe','AWS Transcribe — speech to text','https://transcribe.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['amazon-polly','AWS Polly — text to speech','https://polly.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['amazon-translate','AWS Translate — neural machine translation','https://translate.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['amazon-sagemaker','AWS SageMaker — ML training/deployment','https://api.sagemaker.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['azure-speech','Azure Speech Services — TTS/STT','https://eastus.api.cognitive.microsoft.com','bearer','AZURE_SPEECH_KEY'],
    ['azure-vision','Azure Computer Vision','https://eastus.api.cognitive.microsoft.com/vision/v3.2','bearer','AZURE_VISION_KEY'],
    ['azure-language','Azure Language Service — NLU, sentiment','https://eastus.api.cognitive.microsoft.com/language','bearer','AZURE_LANGUAGE_KEY'],
    ['azure-translator','Azure Translator — machine translation','https://api.cognitive.microsofttranslator.com','bearer','AZURE_TRANSLATOR_KEY'],
    ['azure-form-recognizer','Azure Form Recognizer — document AI','https://eastus.api.cognitive.microsoft.com/formrecognizer','bearer','AZURE_FORM_KEY'],
    ['google-cloud-vision','GCP Vision API — image analysis','https://vision.googleapis.com/v1','bearer','GCP_TOKEN'],
    ['google-cloud-speech','GCP Speech-to-Text','https://speech.googleapis.com/v1','bearer','GCP_TOKEN'],
    ['google-cloud-tts','GCP Text-to-Speech','https://texttospeech.googleapis.com/v1','bearer','GCP_TOKEN'],
    ['google-cloud-translate','GCP Translation API','https://translation.googleapis.com/language/translate/v2','bearer','GCP_TOKEN'],
    ['google-cloud-nlp','GCP Natural Language API','https://language.googleapis.com/v1','bearer','GCP_TOKEN'],
    ['google-cloud-documentai','GCP Document AI','https://documentai.googleapis.com/v1','bearer','GCP_TOKEN'],
    ['nvidia-nim','NVIDIA NIM — GPU-optimized AI microservices','https://integrate.api.nvidia.com/v1','bearer','NVIDIA_API_KEY'],
    ['nvidia-nemo','NVIDIA NeMo — speech AI','https://api.nemo.nvidia.com/v1','bearer','NVIDIA_API_KEY'],
    ['clarifai','Clarifai — visual AI platform','https://api.clarifai.com/v2','bearer','CLARIFAI_PAT'],
    ['roboflow','Roboflow — computer vision pipeline','https://detect.roboflow.com','bearer','ROBOFLOW_API_KEY'],
    ['scale-ai','Scale AI — data labeling, RLHF','https://api.scale.com/v1','bearer','SCALE_API_KEY'],
    ['labelbox','Labelbox — data labeling platform','https://api.labelbox.com/graphql','bearer','LABELBOX_API_KEY'],
    ['snorkel-ai','Snorkel AI — data-centric AI','https://api.snorkel.ai/v1','bearer','SNORKEL_API_KEY'],
    ['comet-ml','Comet ML — experiment tracking','https://www.comet.com/api/rest/v2','bearer','COMET_API_KEY'],
    ['neptune-ai','Neptune.ai — ML metadata store','https://app.neptune.ai/api','bearer','NEPTUNE_API_TOKEN'],
    ['mlflow-cloud','MLflow — ML lifecycle management','https://mlflow.YOUR_DOMAIN.com/api/2.0','bearer','MLFLOW_TOKEN'],
    ['determined-ai','Determined AI — ML training platform','http://localhost:8080/api/v1','bearer','DET_MASTER_TOKEN'],
    ['ray-serve','Ray Serve — scalable model serving','http://localhost:8000','none',null],
    ['bentoml','BentoML — model serving framework','http://localhost:3000','none',null],
    ['seldon-core','Seldon Core — ML deployment','http://localhost:8000/api/v1.0','none',null],
    ['torchserve','TorchServe — PyTorch model serving','http://localhost:8080','none',null],
    ['triton-inference','NVIDIA Triton Inference Server','http://localhost:8000/v2','none',null],
    ['litellm','LiteLLM — unified LLM proxy','http://localhost:4000','bearer','LITELLM_KEY'],
    ['helicone','Helicone — LLM observability','https://api.helicone.ai/v1','bearer','HELICONE_API_KEY'],
    ['promptlayer','PromptLayer — prompt management','https://api.promptlayer.com','bearer','PROMPTLAYER_API_KEY'],
    ['humanloop','Humanloop — LLM app management','https://api.humanloop.com/v4','bearer','HUMANLOOP_API_KEY'],
    ['dspy-cloud','DSPy — programming with LLMs','http://localhost:7860','none',null],
    ['crewai','CrewAI — multi-agent orchestration','http://localhost:8000','none',null],
    ['autogen','AutoGen — multi-agent conversation','http://localhost:8081','none',null],
    ['langfuse','Langfuse — LLM observability','https://cloud.langfuse.com/api','bearer','LANGFUSE_API_KEY'],
    ['traceloop','Traceloop — LLM tracing','https://api.traceloop.com','bearer','TRACELOOP_API_KEY'],
    ['opik','Opik — LLM eval platform','https://api.opik.ai/v1','bearer','OPIK_API_KEY'],
    ['braintrust','Braintrust — AI eval framework','https://api.braintrustdata.com/v1','bearer','BRAINTRUST_API_KEY'],
    ['cartesia','Cartesia — low-latency TTS','https://api.cartesia.ai','bearer','CARTESIA_API_KEY'],
    ['playht','PlayHT — text-to-speech','https://api.play.ht/api/v2','bearer','PLAYHT_API_KEY'],
    ['resemble-ai','Resemble AI — voice cloning','https://app.resemble.ai/api/v2','bearer','RESEMBLE_API_KEY'],
    ['murf-ai','Murf AI — AI voiceover','https://api.murf.ai/v1','bearer','MURF_API_KEY'],
    ['speechify','Speechify — TTS engine','https://api.speechify.com/v1','bearer','SPEECHIFY_API_KEY'],
    ['luma-ai','Luma AI — 3D/video generation','https://api.lumalabs.ai/dream-machine/v1','bearer','LUMA_API_KEY'],
    ['pika-labs','Pika — AI video generation','https://api.pika.art/v1','bearer','PIKA_API_KEY'],
    ['suno-ai','Suno — AI music generation','https://api.suno.ai/v1','bearer','SUNO_API_KEY'],
    ['udio','Udio — AI music creation','https://api.udio.com/v1','bearer','UDIO_API_KEY'],
    ['ideogram','Ideogram — AI image generation','https://api.ideogram.ai/api/v1','bearer','IDEOGRAM_API_KEY'],
    ['flux-pro','Flux Pro — image generation','https://api.bfl.ml/v1','bearer','FLUX_API_KEY'],
    ['leonardo-ai','Leonardo AI — creative AI','https://cloud.leonardo.ai/api/rest/v1','bearer','LEONARDO_API_KEY'],
    ['photoroom','Photoroom — AI photo editing','https://sdk.photoroom.com/v1','custom','PHOTOROOM_API_KEY'],
    ['remove-bg','Remove.bg — background removal','https://api.remove.bg/v1.0','custom','REMOVEBG_API_KEY'],
    ['ocr-space','OCR.space — optical character recognition','https://api.ocr.space/parse','custom','OCR_API_KEY'],
    ['mathpix','Mathpix — document/math OCR','https://api.mathpix.com/v3','custom','MATHPIX_APP_KEY'],
    ['roboflow-inference','Roboflow Inference — object detection','https://detect.roboflow.com','bearer','ROBOFLOW_API_KEY'],
    ['ultralytics','Ultralytics HUB — YOLO models','https://api.ultralytics.com/v1','bearer','ULTRALYTICS_API_KEY'],
  ],

  CLOUD: [
    ['aws-eks','AWS EKS — Kubernetes service','https://eks.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['aws-rds','AWS RDS — managed databases','https://rds.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['aws-elasticache','AWS ElastiCache — in-memory cache','https://elasticache.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['aws-kinesis','AWS Kinesis — real-time streaming','https://kinesis.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['aws-step-functions','AWS Step Functions — serverless orchestration','https://states.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['aws-eventbridge','AWS EventBridge — event bus','https://events.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['aws-apprunner','AWS App Runner — container hosting','https://apprunner.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['aws-amplify','AWS Amplify — fullstack hosting','https://amplify.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['aws-lightsail','AWS Lightsail — simple cloud hosting','https://lightsail.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['aws-cognito','AWS Cognito — user authentication','https://cognito-idp.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['aws-appsync','AWS AppSync — managed GraphQL','https://YOUR_ID.appsync-api.us-east-1.amazonaws.com/graphql','custom','AWS_ACCESS_KEY'],
    ['aws-codepipeline','AWS CodePipeline — CI/CD','https://codepipeline.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['aws-codebuild','AWS CodeBuild — build service','https://codebuild.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['aws-ecr','AWS ECR — container registry','https://ecr.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['aws-elasticbeanstalk','AWS Elastic Beanstalk — PaaS','https://elasticbeanstalk.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['aws-glue','AWS Glue — ETL service','https://glue.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['aws-athena','AWS Athena — serverless SQL','https://athena.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['aws-redshift','AWS Redshift — data warehouse','https://redshift.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['aws-opensearch','AWS OpenSearch — search and analytics','https://es.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['aws-msk','AWS MSK — managed Kafka','https://kafka.us-east-1.amazonaws.com','custom','AWS_ACCESS_KEY'],
    ['azure-aks','Azure AKS — Kubernetes','https://management.azure.com','bearer','AZURE_TOKEN'],
    ['azure-sql','Azure SQL Database','https://management.azure.com','bearer','AZURE_TOKEN'],
    ['azure-redis','Azure Cache for Redis','https://management.azure.com','bearer','AZURE_TOKEN'],
    ['azure-service-bus','Azure Service Bus — messaging','https://YOUR_NS.servicebus.windows.net','bearer','AZURE_SB_TOKEN'],
    ['azure-event-hubs','Azure Event Hubs — event streaming','https://YOUR_NS.servicebus.windows.net','bearer','AZURE_EH_TOKEN'],
    ['azure-container-apps','Azure Container Apps — serverless containers','https://management.azure.com','bearer','AZURE_TOKEN'],
    ['azure-static-web','Azure Static Web Apps','https://management.azure.com','bearer','AZURE_TOKEN'],
    ['azure-key-vault','Azure Key Vault — secrets','https://YOUR_VAULT.vault.azure.net','bearer','AZURE_TOKEN'],
    ['azure-monitor','Azure Monitor — observability','https://management.azure.com','bearer','AZURE_TOKEN'],
    ['azure-logic-apps','Azure Logic Apps — workflow automation','https://management.azure.com','bearer','AZURE_TOKEN'],
    ['gcp-cloud-functions','GCP Cloud Functions — serverless','https://cloudfunctions.googleapis.com/v2','bearer','GCP_TOKEN'],
    ['gcp-gke','GCP GKE — Kubernetes','https://container.googleapis.com/v1','bearer','GCP_TOKEN'],
    ['gcp-cloud-sql','GCP Cloud SQL — managed databases','https://sqladmin.googleapis.com/v1','bearer','GCP_TOKEN'],
    ['gcp-memorystore','GCP Memorystore — managed Redis','https://redis.googleapis.com/v1','bearer','GCP_TOKEN'],
    ['gcp-dataflow','GCP Dataflow — stream processing','https://dataflow.googleapis.com/v1b3','bearer','GCP_TOKEN'],
    ['gcp-spanner','GCP Cloud Spanner — global SQL','https://spanner.googleapis.com/v1','bearer','GCP_TOKEN'],
    ['gcp-secret-manager','GCP Secret Manager','https://secretmanager.googleapis.com/v1','bearer','GCP_TOKEN'],
    ['gcp-cloud-tasks','GCP Cloud Tasks — task queues','https://cloudtasks.googleapis.com/v2','bearer','GCP_TOKEN'],
    ['gcp-scheduler','GCP Cloud Scheduler — cron jobs','https://cloudscheduler.googleapis.com/v1','bearer','GCP_TOKEN'],
    ['gcp-artifact-registry','GCP Artifact Registry — container/package registry','https://artifactregistry.googleapis.com/v1','bearer','GCP_TOKEN'],
    ['vultr','Vultr — cloud compute','https://api.vultr.com/v2','bearer','VULTR_API_KEY'],
    ['hetzner','Hetzner Cloud — European cloud','https://api.hetzner.cloud/v1','bearer','HETZNER_API_TOKEN'],
    ['oracle-cloud','Oracle Cloud Infrastructure','https://iaas.us-ashburn-1.oraclecloud.com/20160918','bearer','OCI_TOKEN'],
    ['ibm-cloud','IBM Cloud — enterprise cloud','https://api.us-south.cf.cloud.ibm.com','bearer','IBM_API_KEY'],
    ['scaleway','Scaleway — European cloud','https://api.scaleway.com','bearer','SCW_SECRET_KEY'],
    ['ovh-cloud','OVH Cloud — European provider','https://api.ovh.com/1.0','custom','OVH_APP_SECRET'],
    ['civo','Civo — Kubernetes-native cloud','https://api.civo.com/v2','bearer','CIVO_API_KEY'],
    ['equinix-metal','Equinix Metal — bare metal cloud','https://api.equinix.com/metal/v1','bearer','EQUINIX_TOKEN'],
    ['backblaze-b2','Backblaze B2 — object storage','https://api.backblazeb2.com/b2api/v2','bearer','B2_AUTH_TOKEN'],
    ['wasabi','Wasabi — hot cloud storage','https://s3.wasabisys.com','custom','WASABI_ACCESS_KEY'],
    ['deno-deploy','Deno Deploy — edge JavaScript','https://api.deno.com/v1','bearer','DENO_DEPLOY_TOKEN'],
    ['val-town','Val Town — serverless functions','https://api.val.town/v1','bearer','VALTOWN_TOKEN'],
    ['replit','Replit — cloud development','https://api.replit.com/v0','bearer','REPLIT_TOKEN'],
    ['github-codespaces','GitHub Codespaces — cloud dev environments','https://api.github.com/user/codespaces','bearer','GITHUB_TOKEN'],
    ['gitpod','Gitpod — cloud dev environments','https://gitpod.io/api','bearer','GITPOD_TOKEN'],
  ],

  DEVTOOLS: [
    ['github-actions','GitHub Actions — CI/CD workflows','https://api.github.com','bearer','GITHUB_TOKEN'],
    ['github-packages','GitHub Packages — package registry','https://api.github.com','bearer','GITHUB_TOKEN'],
    ['github-copilot','GitHub Copilot — AI code assistant','https://api.githubcopilot.com','bearer','GITHUB_TOKEN'],
    ['vercel-ci','Vercel — deployment and CI','https://api.vercel.com','bearer','VERCEL_TOKEN'],
    ['cloudflare-pages','Cloudflare Pages — JAMstack hosting','https://api.cloudflare.com/client/v4','bearer','CF_API_TOKEN'],
    ['semaphore-ci','Semaphore CI — fast CI/CD','https://YOUR_ORG.semaphoreci.com/api/v1alpha','bearer','SEMAPHORE_TOKEN'],
    ['buildkite','Buildkite — CI/CD platform','https://api.buildkite.com/v2','bearer','BUILDKITE_TOKEN'],
    ['drone-ci','Drone CI — container-native CI/CD','http://localhost:8080/api','bearer','DRONE_TOKEN'],
    ['woodpecker-ci','Woodpecker CI — lightweight CI','http://localhost:8000/api','bearer','WOODPECKER_TOKEN'],
    ['teamcity','TeamCity — CI/CD server','https://YOUR_SERVER.jetbrains.space','bearer','TEAMCITY_TOKEN'],
    ['gitlab-ci','GitLab CI/CD — integrated CI/CD','https://gitlab.com/api/v4','bearer','GITLAB_TOKEN'],
    ['renovate','Renovate — dependency updates','https://app.renovatebot.com/api','bearer','RENOVATE_TOKEN'],
    ['dependabot','Dependabot — dependency updates','https://api.github.com','bearer','GITHUB_TOKEN'],
    ['depot','Depot — fast Docker builds','https://api.depot.dev/v1','bearer','DEPOT_TOKEN'],
    ['earthly','Earthly — CI/CD framework','https://api.earthly.dev/v1','bearer','EARTHLY_TOKEN'],
    ['dagger','Dagger — programmable CI/CD','http://localhost:8080','none',null],
    ['turborepo','Turborepo — monorepo build system','https://api.vercel.com','bearer','VERCEL_TOKEN'],
    ['nx-cloud','Nx Cloud — distributed task execution','https://cloud.nx.app/api','bearer','NX_CLOUD_TOKEN'],
    ['chromatic','Chromatic — visual testing for Storybook','https://www.chromatic.com/api/v1','bearer','CHROMATIC_TOKEN'],
    ['cypress-cloud','Cypress Cloud — E2E testing','https://cloud.cypress.io/api','bearer','CYPRESS_TOKEN'],
    ['playwright-service','Playwright — browser testing','http://localhost:9323','none',null],
    ['browserstack','BrowserStack — cross-browser testing','https://api.browserstack.com','basic','BROWSERSTACK_KEY'],
    ['sauce-labs','Sauce Labs — automated testing','https://api.us-west-1.saucelabs.com/rest/v1','basic','SAUCE_KEY'],
    ['k6-cloud','k6 Cloud — load testing','https://api.k6.io/v3','bearer','K6_CLOUD_TOKEN'],
    ['artillery','Artillery — load testing','https://app.artillery.io/api/v1','bearer','ARTILLERY_TOKEN'],
    ['semgrep','Semgrep — static analysis','https://semgrep.dev/api/v1','bearer','SEMGREP_TOKEN'],
    ['trivy','Trivy — vulnerability scanner','http://localhost:4954','none',null],
    ['grype','Grype — vulnerability scanner','http://localhost:8080','none',null],
    ['gitleaks','Gitleaks — secret scanning','http://localhost:8080','none',null],
    ['gitguardian','GitGuardian — secret detection','https://api.gitguardian.com/v1','bearer','GITGUARDIAN_TOKEN'],
    ['trunk','Trunk — code quality platform','https://api.trunk.io/v1','bearer','TRUNK_TOKEN'],
    ['codeclimate','Code Climate — quality analysis','https://api.codeclimate.com/v1','bearer','CODECLIMATE_TOKEN'],
    ['deepsource','DeepSource — code analysis','https://api.deepsource.io/graphql','bearer','DEEPSOURCE_TOKEN'],
    ['figma','Figma — design platform API','https://api.figma.com/v1','bearer','FIGMA_TOKEN'],
    ['storybook','Storybook — UI component library','http://localhost:6006','none',null],
    ['swagger-hub','SwaggerHub — API design','https://api.swaggerhub.com/apis','bearer','SWAGGERHUB_KEY'],
    ['stoplight','Stoplight — API design and docs','https://stoplight.io/api/v1','bearer','STOPLIGHT_TOKEN'],
    ['readme-io','ReadMe — API documentation','https://dash.readme.com/api/v1','basic','README_API_KEY'],
    ['gitbook','GitBook — documentation platform','https://api.gitbook.com/v1','bearer','GITBOOK_TOKEN'],
    ['mintlify','Mintlify — documentation platform','https://api.mintlify.com/v1','bearer','MINTLIFY_TOKEN'],
  ],

  DATA: [
    ['supabase-db','Supabase PostgreSQL — hosted Postgres','https://YOUR_PROJECT.supabase.co/rest/v1','bearer','SUPABASE_KEY'],
    ['hasura','Hasura — instant GraphQL API','https://YOUR_PROJECT.hasura.app/v1/graphql','bearer','HASURA_ADMIN_SECRET'],
    ['prisma-cloud','Prisma Cloud — database toolkit','https://api.prisma.io','bearer','PRISMA_TOKEN'],
    ['xata','Xata — serverless database','https://YOUR_WORKSPACE.xata.sh/db','bearer','XATA_API_KEY'],
    ['tinybird','Tinybird — real-time analytics','https://api.tinybird.co/v0','bearer','TINYBIRD_TOKEN'],
    ['motherduck','MotherDuck — serverless DuckDB','https://api.motherduck.com/v1','bearer','MOTHERDUCK_TOKEN'],
    ['materialize','Materialize — streaming SQL','http://localhost:6875','none',null],
    ['questdb','QuestDB — time-series SQL','http://localhost:9000','none',null],
    ['singlestore','SingleStore — distributed SQL','https://api.singlestore.com/v2','bearer','SINGLESTORE_KEY'],
    ['yugabytedb','YugabyteDB — distributed SQL','http://localhost:7000','none',null],
    ['vitess','Vitess — MySQL scaling','http://localhost:15000','none',null],
    ['mariadb','MariaDB — relational database','http://localhost:3306','custom','MARIADB_PASSWORD'],
    ['couchdb','CouchDB — document database','http://localhost:5984','basic','COUCHDB_PASSWORD'],
    ['rethinkdb','RethinkDB — real-time database','http://localhost:8080','none',null],
    ['scylladb','ScyllaDB — high-performance NoSQL','http://localhost:10000','none',null],
    ['foundationdb','FoundationDB — distributed key-value store','http://localhost:4500','none',null],
    ['tigrisdata','Tigris — serverless NoSQL','https://api.preview.tigrisdata.cloud','bearer','TIGRIS_TOKEN'],
    ['convex','Convex — serverless backend','https://YOUR_PROJECT.convex.cloud','bearer','CONVEX_TOKEN'],
    ['appwrite','Appwrite — backend-as-a-service','https://cloud.appwrite.io/v1','custom','APPWRITE_API_KEY'],
    ['firebase','Firebase — Google BaaS','https://firebaseio.com','bearer','FIREBASE_TOKEN'],
    ['pocketbase','PocketBase — open-source BaaS','http://localhost:8090/api','bearer','POCKETBASE_TOKEN'],
    ['directus','Directus — headless CMS/BaaS','http://localhost:8055','bearer','DIRECTUS_TOKEN'],
    ['strapi','Strapi — headless CMS','http://localhost:1337/api','bearer','STRAPI_TOKEN'],
    ['sanity','Sanity — structured content','https://YOUR_PROJECT.api.sanity.io/v2024-01-01','bearer','SANITY_TOKEN'],
    ['contentful','Contentful — content platform','https://api.contentful.com','bearer','CONTENTFUL_TOKEN'],
    ['storyblok','Storyblok — headless CMS','https://api.storyblok.com/v2','bearer','STORYBLOK_TOKEN'],
    ['hygraph','Hygraph (GraphCMS) — federated content','https://YOUR_REGION.hygraph.com','bearer','HYGRAPH_TOKEN'],
    ['payload-cms','Payload CMS — headless CMS','http://localhost:3000/api','bearer','PAYLOAD_TOKEN'],
    ['keystonejs','KeystoneJS — headless CMS','http://localhost:3000/api/graphql','bearer','KEYSTONE_TOKEN'],
    ['ghost','Ghost — publishing platform','https://YOUR_DOMAIN.ghost.io/ghost/api/admin','bearer','GHOST_ADMIN_KEY'],
  ],

  COMMUNICATION: [
    ['matrix','Matrix — decentralized messaging','https://matrix.org/_matrix/client/v3','bearer','MATRIX_TOKEN'],
    ['signal-cli','Signal CLI — encrypted messaging','http://localhost:8080/v2','none',null],
    ['mastodon','Mastodon — federated social','https://mastodon.social/api/v1','bearer','MASTODON_TOKEN'],
    ['bluesky','Bluesky — AT Protocol social','https://bsky.social/xrpc','bearer','BLUESKY_TOKEN'],
    ['nostr','Nostr — decentralized social','https://relay.damus.io','none',null],
    ['rocket-chat','Rocket.Chat — team messaging','https://YOUR_SERVER.rocket.chat/api/v1','bearer','ROCKETCHAT_TOKEN'],
    ['mattermost','Mattermost — team collaboration','https://YOUR_SERVER.mattermost.com/api/v4','bearer','MATTERMOST_TOKEN'],
    ['zulip','Zulip — team chat','https://YOUR_ORG.zulipchat.com/api/v1','basic','ZULIP_API_KEY'],
    ['stream-chat','Stream Chat — in-app messaging','https://chat.stream-io-api.com','bearer','STREAM_API_KEY'],
    ['sendbird','Sendbird — in-app chat','https://api-YOUR_APP.sendbird.com/v3','bearer','SENDBIRD_TOKEN'],
    ['telnyx','Telnyx — communications platform','https://api.telnyx.com/v2','bearer','TELNYX_API_KEY'],
    ['messagebird','MessageBird — omnichannel comms','https://rest.messagebird.com','custom','MESSAGEBIRD_KEY'],
    ['plivo','Plivo — voice and SMS','https://api.plivo.com/v1','basic','PLIVO_AUTH_TOKEN'],
    ['bandwidth','Bandwidth — communications APIs','https://messaging.bandwidth.com/api/v2','basic','BANDWIDTH_TOKEN'],
    ['mailchimp','Mailchimp — email marketing','https://YOUR_DC.api.mailchimp.com/3.0','bearer','MAILCHIMP_API_KEY'],
    ['convertkit','ConvertKit — email marketing','https://api.convertkit.com/v3','api_key_query','CONVERTKIT_API_KEY'],
    ['beehiiv','Beehiiv — newsletter platform','https://api.beehiiv.com/v2','bearer','BEEHIIV_API_KEY'],
    ['buttondown','Buttondown — newsletter','https://api.buttondown.email/v1','bearer','BUTTONDOWN_TOKEN'],
    ['customer-io','Customer.io — messaging automation','https://api.customer.io/v1','bearer','CUSTOMERIO_API_KEY'],
    ['onesignal','OneSignal — push notifications','https://onesignal.com/api/v1','bearer','ONESIGNAL_API_KEY'],
    ['pushover','Pushover — push notifications','https://api.pushover.net/1','custom','PUSHOVER_TOKEN'],
    ['ntfy','Ntfy — notification service','https://ntfy.sh','none',null],
    ['gotify','Gotify — push notifications','http://localhost:8080','bearer','GOTIFY_TOKEN'],
    ['webex','Webex — video conferencing','https://webexapis.com/v1','bearer','WEBEX_TOKEN'],
    ['zoom','Zoom — video conferencing','https://api.zoom.us/v2','bearer','ZOOM_TOKEN'],
    ['livekit','LiveKit — real-time video/audio','https://YOUR_SERVER.livekit.cloud/twirp','bearer','LIVEKIT_API_KEY'],
    ['daily-co','Daily.co — video call API','https://api.daily.co/v1','bearer','DAILY_API_KEY'],
    ['agora','Agora — real-time engagement','https://api.agora.io/v1','bearer','AGORA_TOKEN'],
    ['crisp','Crisp — customer messaging','https://api.crisp.chat/v1','bearer','CRISP_TOKEN'],
    ['drift','Drift — conversational marketing','https://driftapi.com','bearer','DRIFT_TOKEN'],
  ],

  FINANCE: [
    ['wise','Wise (TransferWise) — international payments','https://api.transferwise.com/v3','bearer','WISE_API_TOKEN'],
    ['revolut','Revolut Business — banking API','https://b2b.revolut.com/api/1.0','bearer','REVOLUT_TOKEN'],
    ['mercury','Mercury — business banking','https://api.mercury.com/api/v1','bearer','MERCURY_TOKEN'],
    ['brex','Brex — corporate cards and spend','https://platform.brexapis.com/v2','bearer','BREX_TOKEN'],
    ['ramp','Ramp — corporate cards','https://api.ramp.com/v1','bearer','RAMP_API_KEY'],
    ['quickbooks','QuickBooks — accounting','https://quickbooks.api.intuit.com/v3','bearer','QUICKBOOKS_TOKEN'],
    ['xero','Xero — accounting platform','https://api.xero.com/api.xro/2.0','bearer','XERO_TOKEN'],
    ['freshbooks','FreshBooks — invoicing','https://api.freshbooks.com','bearer','FRESHBOOKS_TOKEN'],
    ['wave','Wave — small business accounting','https://gql.waveapps.com/graphql/public','bearer','WAVE_TOKEN'],
    ['lemon-squeezy','Lemon Squeezy — digital payments','https://api.lemonsqueezy.com/v1','bearer','LEMONSQUEEZY_KEY'],
    ['paddle','Paddle — payment infrastructure','https://api.paddle.com','bearer','PADDLE_API_KEY'],
    ['chargebee','Chargebee — subscription billing','https://YOUR_SITE.chargebee.com/api/v2','basic','CHARGEBEE_API_KEY'],
    ['recurly','Recurly — subscription management','https://v3.recurly.com','bearer','RECURLY_API_KEY'],
    ['zuora','Zuora — subscription economy','https://rest.zuora.com/v1','bearer','ZUORA_TOKEN'],
    ['gocardless','GoCardless — bank payments','https://api.gocardless.com','bearer','GOCARDLESS_TOKEN'],
    ['adyen','Adyen — payment platform','https://checkout-test.adyen.com/v71','custom','ADYEN_API_KEY'],
    ['mollie','Mollie — EU payments','https://api.mollie.com/v2','bearer','MOLLIE_API_KEY'],
    ['klarna','Klarna — buy now pay later','https://api.klarna.com','basic','KLARNA_API_KEY'],
    ['afterpay','Afterpay — BNPL','https://global-api.afterpay.com/v2','bearer','AFTERPAY_TOKEN'],
    ['kraken','Kraken — crypto exchange','https://api.kraken.com/0','custom','KRAKEN_API_KEY'],
    ['ftx','FTX/Backpack — crypto exchange','https://api.backpack.exchange/api/v1','custom','BACKPACK_API_KEY'],
    ['kucoin','KuCoin — crypto exchange','https://api.kucoin.com/api/v1','custom','KUCOIN_API_KEY'],
    ['bybit','Bybit — crypto derivatives','https://api.bybit.com/v5','custom','BYBIT_API_KEY'],
    ['okx','OKX — crypto exchange','https://www.okx.com/api/v5','custom','OKX_API_KEY'],
    ['uniswap','Uniswap — DEX protocol','https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3','none',null],
    ['aave','Aave — DeFi lending','https://api.thegraph.com/subgraphs/name/aave/protocol-v3','none',null],
    ['etherscan','Etherscan — Ethereum explorer','https://api.etherscan.io/api','api_key_query','ETHERSCAN_API_KEY'],
    ['alchemy','Alchemy — Web3 infrastructure','https://YOUR_NETWORK.g.alchemy.com/v2','bearer','ALCHEMY_API_KEY'],
    ['infura','Infura — Ethereum node provider','https://mainnet.infura.io/v3','custom','INFURA_PROJECT_ID'],
    ['quicknode','QuickNode — blockchain nodes','https://YOUR_ENDPOINT.quiknode.pro','bearer','QUICKNODE_TOKEN'],
    ['chainlink','Chainlink — oracle network','https://api.chain.link/v1','none',null],
    ['the-graph','The Graph — blockchain indexing','https://gateway.thegraph.com/api','bearer','GRAPH_API_KEY'],
    ['covalent','Covalent — blockchain data','https://api.covalenthq.com/v1','bearer','COVALENT_API_KEY'],
    ['dune','Dune Analytics — on-chain analytics','https://api.dune.com/api/v1','bearer','DUNE_API_KEY'],
    ['nansen','Nansen — blockchain analytics','https://api.nansen.ai/v1','bearer','NANSEN_API_KEY'],
    ['tradingview','TradingView — financial charts','https://api.tradingview.com','bearer','TV_TOKEN'],
    ['yahoo-finance','Yahoo Finance — market data','https://query1.finance.yahoo.com/v8','none',null],
    ['alpha-vantage','Alpha Vantage — financial data','https://www.alphavantage.co/query','api_key_query','ALPHAVANTAGE_KEY'],
    ['iex-cloud','IEX Cloud — financial data','https://cloud.iexapis.com/stable','bearer','IEX_TOKEN'],
    ['finnhub','Finnhub — stock market data','https://finnhub.io/api/v1','bearer','FINNHUB_API_KEY'],
  ],

  SECURITY: [
    ['nmap-api','Nmap — network scanner','http://localhost:8080','none',null],
    ['nuclei','Nuclei — vulnerability scanner','http://localhost:8080','none',null],
    ['burpsuite','Burp Suite — web security testing','http://localhost:8080','bearer','BURP_TOKEN'],
    ['zap-proxy','ZAP Proxy — web app scanner','http://localhost:8080','custom','ZAP_API_KEY'],
    ['metasploit','Metasploit — penetration testing','https://localhost:3790/api/v1','bearer','MSF_TOKEN'],
    ['qualys','Qualys — cloud security','https://qualysapi.qualys.com/api/2.0','basic','QUALYS_TOKEN'],
    ['tenable','Tenable — vulnerability management','https://cloud.tenable.com','custom','TENABLE_API_KEY'],
    ['rapid7','Rapid7 InsightVM — vulnerability mgmt','https://us.api.insight.rapid7.com','custom','RAPID7_API_KEY'],
    ['wiz','Wiz — cloud security','https://api.wiz.io/graphql','bearer','WIZ_TOKEN'],
    ['lacework','Lacework — cloud security','https://YOUR_ACCOUNT.lacework.net/api/v2','bearer','LACEWORK_TOKEN'],
    ['prisma-cloud-sec','Prisma Cloud — cloud security','https://api.prismacloud.io','bearer','PRISMA_CLOUD_TOKEN'],
    ['snort','Snort — IDS/IPS','http://localhost:8080','none',null],
    ['suricata','Suricata — IDS/IPS','http://localhost:8080','none',null],
    ['elastic-siem','Elastic SIEM — security analytics','http://localhost:5601/api','bearer','ELASTIC_TOKEN'],
    ['splunk-siem','Splunk Enterprise Security','https://YOUR_INSTANCE.splunkcloud.com:8089','bearer','SPLUNK_TOKEN'],
    ['misp','MISP — threat intelligence','https://YOUR_MISP.local','bearer','MISP_AUTH_KEY'],
    ['alienvault-otx','AlienVault OTX — threat intel','https://otx.alienvault.com/api/v1','custom','OTX_API_KEY'],
    ['abuse-ipdb','AbuseIPDB — IP reputation','https://api.abuseipdb.com/api/v2','custom','ABUSEIPDB_KEY'],
    ['urlscan','URLScan.io — URL analysis','https://urlscan.io/api/v1','bearer','URLSCAN_API_KEY'],
    ['greynoise','GreyNoise — internet scanner intel','https://api.greynoise.io/v3','bearer','GREYNOISE_API_KEY'],
    ['censys','Censys — internet scan data','https://search.censys.io/api/v2','basic','CENSYS_API_KEY'],
    ['binary-edge','BinaryEdge — internet scanning','https://api.binaryedge.io/v2','bearer','BINARYEDGE_TOKEN'],
    ['securitytrails','SecurityTrails — DNS intelligence','https://api.securitytrails.com/v1','custom','SECURITYTRAILS_KEY'],
    ['dehashed','Dehashed — breach search','https://api.dehashed.com','basic','DEHASHED_API_KEY'],
    ['spyse','Spyse — internet intelligence','https://api.spyse.com/v4','bearer','SPYSE_TOKEN'],
    ['hunter-io','Hunter.io — email finding','https://api.hunter.io/v2','api_key_query','HUNTER_API_KEY'],
    ['clearbit','Clearbit — business intelligence','https://person.clearbit.com/v2','bearer','CLEARBIT_API_KEY'],
    ['fullcontact','FullContact — identity resolution','https://api.fullcontact.com/v3','bearer','FULLCONTACT_KEY'],
    ['truecaller','Truecaller — caller ID','https://api4.truecaller.com/v1','bearer','TRUECALLER_TOKEN'],
    ['malwarebazaar','MalwareBazaar — malware samples','https://mb-api.abuse.ch/api/v1','none',null],
  ],

  NETWORK: [
    ['cloudflare-waf','Cloudflare WAF — web firewall','https://api.cloudflare.com/client/v4','bearer','CF_API_TOKEN'],
    ['cloudflare-workers','Cloudflare Workers — edge compute','https://api.cloudflare.com/client/v4','bearer','CF_API_TOKEN'],
    ['cloudflare-r2','Cloudflare R2 — object storage','https://api.cloudflare.com/client/v4','bearer','CF_API_TOKEN'],
    ['cloudflare-d1','Cloudflare D1 — edge database','https://api.cloudflare.com/client/v4','bearer','CF_API_TOKEN'],
    ['cloudflare-kv','Cloudflare KV — key-value store','https://api.cloudflare.com/client/v4','bearer','CF_API_TOKEN'],
    ['cloudflare-queues','Cloudflare Queues — message queues','https://api.cloudflare.com/client/v4','bearer','CF_API_TOKEN'],
    ['cloudflare-vectorize','Cloudflare Vectorize — vector DB','https://api.cloudflare.com/client/v4','bearer','CF_API_TOKEN'],
    ['cloudflare-ai','Cloudflare Workers AI — edge inference','https://api.cloudflare.com/client/v4','bearer','CF_API_TOKEN'],
    ['cloudflare-images','Cloudflare Images — image optimization','https://api.cloudflare.com/client/v4','bearer','CF_API_TOKEN'],
    ['cloudflare-stream','Cloudflare Stream — video hosting','https://api.cloudflare.com/client/v4','bearer','CF_API_TOKEN'],
    ['cloudflare-access','Cloudflare Access — zero trust','https://api.cloudflare.com/client/v4','bearer','CF_API_TOKEN'],
    ['istio','Istio — service mesh','http://localhost:15014','none',null],
    ['linkerd','Linkerd — service mesh','http://localhost:8084','none',null],
    ['consul','HashiCorp Consul — service discovery','http://localhost:8500/v1','bearer','CONSUL_TOKEN'],
    ['envoy','Envoy — edge proxy','http://localhost:9901','none',null],
    ['haproxy','HAProxy — load balancer','http://localhost:5555/v2','basic','HAPROXY_TOKEN'],
    ['openvpn','OpenVPN — VPN server','https://YOUR_SERVER:943/api','bearer','OPENVPN_TOKEN'],
    ['zerotier','ZeroTier — virtual networking','https://api.zerotier.com/api/v1','bearer','ZEROTIER_TOKEN'],
    ['netbird','NetBird — mesh VPN','https://api.netbird.io/api','bearer','NETBIRD_TOKEN'],
    ['headscale','Headscale — Tailscale coordinator','http://localhost:8080/api/v1','bearer','HEADSCALE_TOKEN'],
    ['dnsmadeeasy','DNS Made Easy — managed DNS','https://api.dnsmadeeasy.com/V2.0','custom','DNSMADEEASY_KEY'],
    ['route53','Route53 — AWS DNS','https://route53.amazonaws.com/2013-04-01','custom','AWS_ACCESS_KEY'],
    ['dnsimple','DNSimple — DNS hosting','https://api.dnsimple.com/v2','bearer','DNSIMPLE_TOKEN'],
    ['namecheap','Namecheap — domain registrar','https://api.namecheap.com/xml.response','custom','NAMECHEAP_KEY'],
    ['godaddy','GoDaddy — domain management','https://api.godaddy.com/v1','custom','GODADDY_KEY'],
    ['porkbun','Porkbun — domain registrar','https://porkbun.com/api/json/v3','custom','PORKBUN_API_KEY'],
    ['he-dns','Hurricane Electric DNS','https://dns.he.net','custom','HE_DNS_KEY'],
    ['whatsmydns','WhatsMyDNS — DNS propagation','https://api.whatsmydns.net','none',null],
    ['mtr-online','MTR — traceroute','http://localhost:8080','none',null],
    ['speedtest','Speedtest — internet speed','https://www.speedtest.net/api','none',null],
  ],

  MONITORING: [
    ['prometheus-cloud','Prometheus Cloud — managed metrics','https://YOUR_INSTANCE.grafana.net/api/prom','bearer','PROM_TOKEN'],
    ['grafana-cloud','Grafana Cloud — dashboards','https://YOUR_STACK.grafana.net','bearer','GRAFANA_TOKEN'],
    ['datadog-apm','Datadog APM — application monitoring','https://api.datadoghq.com/api/v1','custom','DD_API_KEY'],
    ['elastic-apm','Elastic APM — application monitoring','http://localhost:8200','bearer','ELASTIC_APM_TOKEN'],
    ['dynatrace','Dynatrace — full-stack monitoring','https://YOUR_ENV.live.dynatrace.com/api/v2','bearer','DYNATRACE_TOKEN'],
    ['instana','Instana — APM and observability','https://YOUR_TENANT.instana.io/api','bearer','INSTANA_TOKEN'],
    ['appdynamics','AppDynamics — APM','https://YOUR_ACCOUNT.saas.appdynamics.com','bearer','APPDYNAMICS_TOKEN'],
    ['signoz','SigNoz — open-source APM','http://localhost:3301/api/v3','bearer','SIGNOZ_TOKEN'],
    ['jaeger','Jaeger — distributed tracing','http://localhost:16686/api','none',null],
    ['zipkin','Zipkin — distributed tracing','http://localhost:9411/api/v2','none',null],
    ['axiom','Axiom — log management','https://api.axiom.co/v1','bearer','AXIOM_TOKEN'],
    ['logz-io','Logz.io — log analytics','https://api.logz.io/v1','bearer','LOGZIO_TOKEN'],
    ['coralogix','Coralogix — observability','https://api.coralogix.com','bearer','CORALOGIX_KEY'],
    ['cronitor','Cronitor — cron monitoring','https://cronitor.io/api','bearer','CRONITOR_API_KEY'],
    ['healthchecks-io','Healthchecks.io — cron monitoring','https://healthchecks.io/api/v3','bearer','HEALTHCHECKS_KEY'],
    ['incident-io','Incident.io — incident management','https://api.incident.io/v2','bearer','INCIDENTIO_TOKEN'],
    ['rootly','Rootly — incident management','https://api.rootly.com/v1','bearer','ROOTLY_TOKEN'],
    ['firehydrant','FireHydrant — incident management','https://api.firehydrant.io/v1','bearer','FIREHYDRANT_TOKEN'],
    ['statuspal','StatusPal — status pages','https://statuspal.io/api/v1','bearer','STATUSPAL_TOKEN'],
    ['cachet','Cachet — open status page','http://localhost:8000/api/v1','bearer','CACHET_TOKEN'],
  ],

  MEDIA: [
    ['replicate-media','Replicate — ML model inference','https://api.replicate.com/v1','bearer','REPLICATE_TOKEN'],
    ['bannerbear','Bannerbear — auto-generate images','https://api.bannerbear.com/v2','bearer','BANNERBEAR_KEY'],
    ['placid','Placid — creative automation','https://api.placid.app/api/rest','bearer','PLACID_TOKEN'],
    ['htmlcsstoimage','HTML/CSS to Image — screenshot API','https://hcti.io/v1','basic','HCTI_API_KEY'],
    ['screenshotone','ScreenshotOne — website screenshots','https://api.screenshotone.com','api_key_query','SCREENSHOTONE_KEY'],
    ['browserless','Browserless — headless Chrome','https://chrome.browserless.io','bearer','BROWSERLESS_TOKEN'],
    ['assemblyai-media','AssemblyAI — audio intelligence','https://api.assemblyai.com/v2','bearer','ASSEMBLYAI_KEY'],
    ['rev-ai','Rev AI — speech-to-text','https://api.rev.ai/speechtotext/v1','bearer','REVAI_TOKEN'],
    ['openai-whisper','OpenAI Whisper — transcription','https://api.openai.com/v1','bearer','OPENAI_API_KEY'],
    ['speechmatics','Speechmatics — speech recognition','https://asr.api.speechmatics.com/v2','bearer','SPEECHMATICS_KEY'],
    ['descript','Descript — audio/video editing','https://api.descript.com/v2','bearer','DESCRIPT_TOKEN'],
    ['captions-ai','Captions AI — video captions','https://api.captions.ai/v1','bearer','CAPTIONS_API_KEY'],
    ['heygen','HeyGen — AI video avatars','https://api.heygen.com/v2','bearer','HEYGEN_API_KEY'],
    ['synthesia','Synthesia — AI video generation','https://api.synthesia.io/v2','bearer','SYNTHESIA_API_KEY'],
    ['tavus','Tavus — personalized video','https://api.tavus.io/v2','bearer','TAVUS_API_KEY'],
    ['d-id','D-ID — AI video creation','https://api.d-id.com','bearer','DID_API_KEY'],
    ['unscreen','Unscreen — video background removal','https://api.unscreen.com/v1.0','bearer','UNSCREEN_API_KEY'],
    ['kraken-io','Kraken.io — image optimization','https://api.kraken.io/v1','custom','KRAKEN_IO_KEY'],
    ['tinypng','TinyPNG — image compression','https://api.tinify.com/shrink','basic','TINYPNG_API_KEY'],
    ['imagekit','ImageKit — image CDN','https://api.imagekit.io/v1','basic','IMAGEKIT_KEY'],
    ['uploadthing','UploadThing — file uploads','https://uploadthing.com/api','bearer','UPLOADTHING_TOKEN'],
    ['uploadcare','Uploadcare — file handling','https://api.uploadcare.com/files','bearer','UPLOADCARE_KEY'],
    ['transloadit','Transloadit — file processing','https://api2.transloadit.com','custom','TRANSLOADIT_KEY'],
    ['filestack','Filestack — file handling','https://www.filestackapi.com/api','api_key_query','FILESTACK_KEY'],
    ['picovoice','Picovoice — voice AI','https://api.picovoice.ai/v1','bearer','PICOVOICE_KEY'],
    ['resemble-clone','Resemble AI — voice clone','https://app.resemble.ai/api/v2','bearer','RESEMBLE_TOKEN'],
    ['coqui-tts','Coqui TTS — open-source TTS','http://localhost:5002','none',null],
    ['piper-tts','Piper TTS — local TTS engine','http://localhost:5000','none',null],
    ['whisper-cpp','Whisper.cpp — local speech recognition','http://localhost:8080','none',null],
    ['giphy','GIPHY — GIF search and sharing','https://api.giphy.com/v1','api_key_query','GIPHY_API_KEY'],
  ],

  AUTOMATION: [
    ['activepieces','Activepieces — workflow automation','http://localhost:8080/api/v1','bearer','ACTIVEPIECES_TOKEN'],
    ['huginn','Huginn — agent automation','http://localhost:3000/api','bearer','HUGINN_TOKEN'],
    ['automa','Automa — browser automation','http://localhost:8080','none',null],
    ['browserflow','Browserflow — browser automation','https://api.browserflow.app/v1','bearer','BROWSERFLOW_KEY'],
    ['phantombuster','PhantomBuster — data extraction','https://api.phantombuster.com/api/v2','bearer','PHANTOMBUSTER_KEY'],
    ['apify','Apify — web scraping platform','https://api.apify.com/v2','bearer','APIFY_TOKEN'],
    ['scrapy-cloud','Scrapy Cloud — web scraping','https://app.scrapinghub.com/api','bearer','SCRAPY_API_KEY'],
    ['bright-data','Bright Data — web data','https://api.brightdata.com','bearer','BRIGHTDATA_TOKEN'],
    ['oxylabs','Oxylabs — web scraping','https://realtime.oxylabs.io/v1','basic','OXYLABS_TOKEN'],
    ['scrapingbee','ScrapingBee — web scraping API','https://app.scrapingbee.com/api/v1','api_key_query','SCRAPINGBEE_KEY'],
    ['zyte','Zyte — web scraping','https://api.zyte.com/v1','bearer','ZYTE_API_KEY'],
    ['crawlee','Crawlee — web crawling','http://localhost:8080','none',null],
    ['firecrawl','Firecrawl — web scraping for LLMs','https://api.firecrawl.dev/v1','bearer','FIRECRAWL_API_KEY'],
    ['jina-reader','Jina Reader — URL to markdown','https://r.jina.ai','bearer','JINA_API_KEY'],
    ['browserbase','Browserbase — headless browser','https://api.browserbase.com/v1','bearer','BROWSERBASE_KEY'],
    ['selenium-grid','Selenium Grid — browser automation','http://localhost:4444/wd/hub','none',null],
    ['puppeteer','Puppeteer — headless Chrome','http://localhost:3000','none',null],
    ['playwright-server','Playwright — browser automation','http://localhost:3000','none',null],
    ['locust','Locust — load testing','http://localhost:8089/stats','none',null],
    ['gatling','Gatling — performance testing','http://localhost:9000','none',null],
    ['ifttt','IFTTT — trigger automation','https://maker.ifttt.com/trigger','custom','IFTTT_KEY'],
    ['home-assistant','Home Assistant — smart home','http://localhost:8123/api','bearer','HASS_TOKEN'],
    ['homebridge','Homebridge — HomeKit bridge','http://localhost:8581/api','bearer','HOMEBRIDGE_TOKEN'],
    ['mqtt','MQTT Broker — IoT messaging','http://localhost:1883','basic','MQTT_PASSWORD'],
    ['node-red','Node-RED — flow programming','http://localhost:1880','bearer','NODERED_TOKEN'],
    ['airops','AirOps — AI workflow builder','https://api.airops.com/v1','bearer','AIROPS_TOKEN'],
    ['relevance-ai','Relevance AI — AI workflows','https://api.relevanceai.com/latest','bearer','RELEVANCE_KEY'],
    ['inngest','Inngest — event-driven functions','https://api.inngest.com/v1','bearer','INNGEST_KEY'],
    ['trigger-dev','Trigger.dev — background jobs','https://api.trigger.dev/api/v1','bearer','TRIGGERDEV_KEY'],
    ['qstash','QStash — serverless messaging','https://qstash.upstash.io/v2','bearer','QSTASH_TOKEN'],
  ],

  API: [
    ['twilio-api','Twilio REST API — full platform','https://api.twilio.com','basic','TWILIO_AUTH_TOKEN'],
    ['google-maps','Google Maps Platform','https://maps.googleapis.com/maps/api','api_key_query','GOOGLE_MAPS_KEY'],
    ['mapbox','Mapbox — maps and location','https://api.mapbox.com','api_key_query','MAPBOX_TOKEN'],
    ['here-maps','HERE Maps — location services','https://geocode.search.hereapi.com/v1','api_key_query','HERE_API_KEY'],
    ['openstreetmap','OpenStreetMap — free mapping','https://nominatim.openstreetmap.org','none',null],
    ['weather-api','OpenWeatherMap — weather data','https://api.openweathermap.org/data/2.5','api_key_query','OPENWEATHER_KEY'],
    ['weatherapi','WeatherAPI.com — weather data','https://api.weatherapi.com/v1','api_key_query','WEATHERAPI_KEY'],
    ['ip-api','IP-API — IP geolocation','http://ip-api.com/json','none',null],
    ['abstract-api','Abstract API — data enrichment','https://YOUR_API.abstractapi.com/v1','api_key_query','ABSTRACT_API_KEY'],
    ['newsapi','NewsAPI — news aggregation','https://newsapi.org/v2','api_key_query','NEWSAPI_KEY'],
    ['guardian-api','The Guardian — news API','https://content.guardianapis.com','api_key_query','GUARDIAN_KEY'],
    ['nytimes-api','New York Times — article search','https://api.nytimes.com/svc/search/v2','api_key_query','NYTIMES_KEY'],
    ['unsplash','Unsplash — free images','https://api.unsplash.com','bearer','UNSPLASH_TOKEN'],
    ['pexels','Pexels — free images/video','https://api.pexels.com/v1','bearer','PEXELS_API_KEY'],
    ['pixabay','Pixabay — free media','https://pixabay.com/api','api_key_query','PIXABAY_KEY'],
    ['open-library','Open Library — book data','https://openlibrary.org/api','none',null],
    ['google-books','Google Books — book search','https://www.googleapis.com/books/v1','api_key_query','GOOGLE_BOOKS_KEY'],
    ['tmdb','TMDB — movie database','https://api.themoviedb.org/3','bearer','TMDB_TOKEN'],
    ['omdb','OMDB — movie data','https://www.omdbapi.com','api_key_query','OMDB_KEY'],
    ['yelp','Yelp Fusion — business data','https://api.yelp.com/v3','bearer','YELP_API_KEY'],
    ['google-places','Google Places — location data','https://places.googleapis.com/v1','bearer','GOOGLE_PLACES_KEY'],
    ['foursquare','Foursquare — location intelligence','https://api.foursquare.com/v3','bearer','FOURSQUARE_KEY'],
    ['wolfram-alpha','Wolfram Alpha — computational intelligence','https://api.wolframalpha.com/v2','api_key_query','WOLFRAM_APPID'],
    ['wikipedia','Wikipedia — encyclopedia API','https://en.wikipedia.org/w/api.php','none',null],
    ['arxiv','ArXiv — research papers','https://export.arxiv.org/api','none',null],
    ['semantic-scholar','Semantic Scholar — academic papers','https://api.semanticscholar.org/graph/v1','bearer','S2_API_KEY'],
    ['crossref','Crossref — scholarly metadata','https://api.crossref.org/works','none',null],
    ['openalex','OpenAlex — research data','https://api.openalex.org','none',null],
    ['serper','Serper — Google search API','https://google.serper.dev','bearer','SERPER_API_KEY'],
    ['serpapi','SerpAPI — search engine results','https://serpapi.com/search','api_key_query','SERPAPI_KEY'],
    ['tavily-search','Tavily — AI search API','https://api.tavily.com','bearer','TAVILY_API_KEY'],
    ['exa-search','Exa — neural search','https://api.exa.ai/search','bearer','EXA_API_KEY'],
    ['brave-search','Brave Search — privacy search','https://api.search.brave.com/res/v1','bearer','BRAVE_SEARCH_KEY'],
    ['bing-search','Bing Search — web search','https://api.bing.microsoft.com/v7.0','custom','BING_API_KEY'],
    ['you-search','You.com — AI search','https://api.ydc-index.io','bearer','YOU_API_KEY'],
    ['notion-api','Notion — workspace API','https://api.notion.com/v1','bearer','NOTION_TOKEN'],
    ['trello','Trello — project management','https://api.trello.com/1','api_key_query','TRELLO_KEY'],
    ['asana','Asana — work management','https://app.asana.com/api/1.0','bearer','ASANA_TOKEN'],
    ['monday','Monday.com — work OS','https://api.monday.com/v2','bearer','MONDAY_TOKEN'],
    ['clickup','ClickUp — project management','https://api.clickup.com/api/v2','bearer','CLICKUP_TOKEN'],
    ['basecamp','Basecamp — project management','https://3.basecampapi.com','bearer','BASECAMP_TOKEN'],
    ['todoist','Todoist — task management','https://api.todoist.com/rest/v2','bearer','TODOIST_TOKEN'],
    ['coda','Coda — collaborative docs','https://coda.io/apis/v1','bearer','CODA_TOKEN'],
    ['google-sheets','Google Sheets — spreadsheet API','https://sheets.googleapis.com/v4','bearer','GOOGLE_TOKEN'],
    ['google-drive','Google Drive — file storage API','https://www.googleapis.com/drive/v3','bearer','GOOGLE_TOKEN'],
    ['google-calendar','Google Calendar API','https://www.googleapis.com/calendar/v3','bearer','GOOGLE_TOKEN'],
    ['google-gmail','Gmail API — email','https://gmail.googleapis.com/gmail/v1','bearer','GOOGLE_TOKEN'],
    ['microsoft-graph','Microsoft Graph — M365 data','https://graph.microsoft.com/v1.0','bearer','MS_GRAPH_TOKEN'],
    ['dropbox','Dropbox — file storage','https://api.dropboxapi.com/2','bearer','DROPBOX_TOKEN'],
    ['box','Box — content management','https://api.box.com/2.0','bearer','BOX_TOKEN'],
  ],

  BLOCKCHAIN: [
    ['ethereum-rpc','Ethereum JSON-RPC — mainnet','https://mainnet.infura.io/v3','custom','INFURA_KEY'],
    ['polygon-rpc','Polygon JSON-RPC','https://polygon-rpc.com','none',null],
    ['arbitrum-rpc','Arbitrum JSON-RPC','https://arb1.arbitrum.io/rpc','none',null],
    ['optimism-rpc','Optimism JSON-RPC','https://mainnet.optimism.io','none',null],
    ['base-rpc','Base JSON-RPC','https://mainnet.base.org','none',null],
    ['bsc-rpc','BNB Smart Chain JSON-RPC','https://bsc-dataseed.binance.org','none',null],
    ['avalanche-rpc','Avalanche C-Chain RPC','https://api.avax.network/ext/bc/C/rpc','none',null],
    ['solana-rpc','Solana JSON-RPC','https://api.mainnet-beta.solana.com','none',null],
    ['near-rpc','NEAR Protocol RPC','https://rpc.mainnet.near.org','none',null],
    ['cosmos-rpc','Cosmos Hub RPC','https://rpc.cosmos.network','none',null],
    ['sui-rpc','Sui Move RPC','https://fullnode.mainnet.sui.io','none',null],
    ['aptos-rpc','Aptos Move RPC','https://fullnode.mainnet.aptoslabs.com/v1','none',null],
    ['ton-rpc','TON Blockchain RPC','https://toncenter.com/api/v2','none',null],
    ['tron-rpc','TRON Network API','https://api.trongrid.io','none',null],
    ['fantom-rpc','Fantom RPC','https://rpcapi.fantom.network','none',null],
    ['harmony-rpc','Harmony ONE RPC','https://api.harmony.one','none',null],
    ['hedera-rpc','Hedera Hashgraph','https://mainnet-public.mirrornode.hedera.com/api/v1','none',null],
    ['stellar-rpc','Stellar Horizon API','https://horizon.stellar.org','none',null],
    ['ripple-rpc','XRP Ledger RPC','https://s1.ripple.com:51234','none',null],
    ['cardano-rpc','Cardano — Blockfrost API','https://cardano-mainnet.blockfrost.io/api/v0','bearer','BLOCKFROST_KEY'],
    ['polkadot-rpc','Polkadot RPC','https://rpc.polkadot.io','none',null],
    ['algorand','Algorand — blockchain','https://mainnet-api.algonode.cloud/v2','none',null],
    ['flow-rpc','Flow blockchain','https://rest-mainnet.onflow.org/v1','none',null],
    ['stacks-rpc','Stacks (Bitcoin L2)','https://stacks-node-api.mainnet.stacks.co/v2','none',null],
    ['bitcoin-rpc','Bitcoin Core RPC','http://localhost:8332','basic','BITCOIN_RPC_PASSWORD'],
    ['lightning-rpc','Lightning Network LND','https://localhost:8080/v1','bearer','LND_MACAROON'],
    ['opensea','OpenSea — NFT marketplace','https://api.opensea.io/api/v2','bearer','OPENSEA_API_KEY'],
    ['rarible','Rarible — NFT protocol','https://api.rarible.org/v0.1','bearer','RARIBLE_API_KEY'],
    ['zora','Zora — NFT protocol','https://api.zora.co/graphql','none',null],
    ['nftport','NFTPort — NFT infrastructure','https://api.nftport.xyz/v0','bearer','NFTPORT_API_KEY'],
  ],

  IOT: [
    ['home-assistant-api','Home Assistant — smart home','http://localhost:8123/api','bearer','HASS_TOKEN'],
    ['smartthings','SmartThings — Samsung IoT','https://api.smartthings.com/v1','bearer','SMARTTHINGS_TOKEN'],
    ['tuya','Tuya — IoT platform','https://openapi.tuyaus.com/v1.0','custom','TUYA_ACCESS_KEY'],
    ['particle','Particle — IoT hardware','https://api.particle.io/v1','bearer','PARTICLE_TOKEN'],
    ['arduino-iot','Arduino IoT Cloud','https://api2.arduino.cc/iot/v2','bearer','ARDUINO_TOKEN'],
    ['adafruit-io','Adafruit IO — IoT platform','https://io.adafruit.com/api/v2','custom','ADAFRUIT_IO_KEY'],
    ['thingspeak','ThingSpeak — IoT analytics','https://api.thingspeak.com','api_key_query','THINGSPEAK_KEY'],
    ['blynk','Blynk — IoT platform','https://blynk.cloud/external/api','bearer','BLYNK_TOKEN'],
    ['losant','Losant — enterprise IoT','https://api.losant.com/applications','bearer','LOSANT_TOKEN'],
    ['balena','Balena — IoT fleet management','https://api.balena-cloud.com/v6','bearer','BALENA_TOKEN'],
    ['tasmota','Tasmota — ESP device firmware','http://DEVICE_IP','none',null],
    ['esphome','ESPHome — ESP32/8266 firmware','http://localhost:6052','none',null],
    ['zigbee2mqtt','Zigbee2MQTT — Zigbee bridge','http://localhost:8080/api','none',null],
    ['z-wave-js','Z-Wave JS — Z-Wave controller','http://localhost:3000','bearer','ZWAVE_TOKEN'],
    ['philips-hue','Philips Hue — smart lighting','https://api.meethue.com/route/api','bearer','HUE_TOKEN'],
    ['sonos','Sonos — smart speakers','https://api.ws.sonos.com/control/api/v1','bearer','SONOS_TOKEN'],
    ['ecobee','Ecobee — smart thermostat','https://api.ecobee.com/1','bearer','ECOBEE_TOKEN'],
    ['tesla-api','Tesla — vehicle API','https://fleet-api.prd.na.vn.cloud.tesla.com/api/1','bearer','TESLA_TOKEN'],
    ['roomba','iRobot Roomba — robot vacuum','http://LOCAL_IP','none',null],
    ['ring','Ring — home security','https://api.ring.com','bearer','RING_TOKEN'],
  ],
};

// ============================================================================
// Generate SQL INSERT statements
// ============================================================================

let totalServers = 0;
const sqlStatements = [];

for (const [category, servers] of Object.entries(SERVERS)) {
  const values = servers.map(([name, desc, url, auth, key]) => {
    totalServers++;
    const authKey = key ? `'${key}'` : 'NULL';
    return `('${name}','${category}','${desc.replace(/'/g, "''")}',1,'${url}','${auth}',${authKey},'rest_json',60)`;
  });

  // Chunk into batches of 40
  for (let i = 0; i < values.length; i += 40) {
    const chunk = values.slice(i, i + 40);
    sqlStatements.push(
      `INSERT INTO servers (server_name, category, description, is_cloud, api_base_url, auth_type, auth_key_name, api_pattern, rate_limit_rpm) VALUES\n${chunk.join(',\n')};`
    );
  }
}

console.log(`Total new servers to insert: ${totalServers}`);
console.log(`SQL statements generated: ${sqlStatements.length}`);
console.log('---');

// Output SQL for each batch
sqlStatements.forEach((sql, i) => {
  console.log(`\n-- Batch ${i + 1}`);
  console.log(sql);
});
